version: '3'

dotenv: ['.env']

tasks:
  migrate:
    env:
      DB_FILE: "{{.DB_FILE}}"
      MIGRATIONS_PATH: "{{.MIGRATIONS_PATH}}"
    cmds:
      - go run ./cmd/migrator/main.go

  swag:
    cmds:
      - swag fmt
      - swag init -d ./internal/server -g server.go --pdl 3

  build:
    deps: [swag]
    cmd: go build -o bin/main cmd/main/main.go
    silent: true

  run:
    env:
      CONFIG_PATH: .env
    deps: [build]
    cmd: ./bin/main
    silent: true

  cov:
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out
      - go tool cover -html=coverage.out -o coverage.html
      - rm coverage.out
