// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_service

import (
	"context"

	"github.com/AlexMickh/shop-backend/internal/models"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateUser(ctx context.Context, email string, phone string, password string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, email, phone, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, email, phone, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, email, phone, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, phone, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - phone string
//   - password string
func (_e *MockUserService_Expecter) CreateUser(ctx interface{}, email interface{}, phone interface{}, password interface{}) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, email, phone, password)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(ctx context.Context, email string, phone string, password string)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(uUID uuid.UUID, err error) *MockUserService_CreateUser_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, email string, phone string, password string) (uuid.UUID, error)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UserByEmail provides a mock function for the type MockUserService
func (_mock *MockUserService) UserByEmail(ctx context.Context, email string) (models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UserByEmail")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_UserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByEmail'
type MockUserService_UserByEmail_Call struct {
	*mock.Call
}

// UserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserService_Expecter) UserByEmail(ctx interface{}, email interface{}) *MockUserService_UserByEmail_Call {
	return &MockUserService_UserByEmail_Call{Call: _e.mock.On("UserByEmail", ctx, email)}
}

func (_c *MockUserService_UserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserService_UserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_UserByEmail_Call) Return(user models.User, err error) *MockUserService_UserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_UserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (models.User, error)) *MockUserService_UserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) CreateToken(ctx context.Context, userID uuid.UUID, tokenType models.TokenType) (models.Token, error) {
	ret := _mock.Called(ctx, userID, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 models.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.TokenType) (models.Token, error)); ok {
		return returnFunc(ctx, userID, tokenType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.TokenType) models.Token); ok {
		r0 = returnFunc(ctx, userID, tokenType)
	} else {
		r0 = ret.Get(0).(models.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.TokenType) error); ok {
		r1 = returnFunc(ctx, userID, tokenType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockTokenService_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tokenType models.TokenType
func (_e *MockTokenService_Expecter) CreateToken(ctx interface{}, userID interface{}, tokenType interface{}) *MockTokenService_CreateToken_Call {
	return &MockTokenService_CreateToken_Call{Call: _e.mock.On("CreateToken", ctx, userID, tokenType)}
}

func (_c *MockTokenService_CreateToken_Call) Run(run func(ctx context.Context, userID uuid.UUID, tokenType models.TokenType)) *MockTokenService_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 models.TokenType
		if args[2] != nil {
			arg2 = args[2].(models.TokenType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenService_CreateToken_Call) Return(token models.Token, err error) *MockTokenService_CreateToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenService_CreateToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tokenType models.TokenType) (models.Token, error)) *MockTokenService_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}
